### ISSUE TITLE
Create Exercise Tracker (Backend functionality)

### ISSUE THREAD

**Issue by devlargs** [devlargs/freecodecamp-projects#48]
- [x] Create POST /api/exercise/new-user
- [x] Create GET /api/exercise/users
- [x] Create POST /api/exercise/add/:id
- [x] Create GET /api/exercise/log/_id
