### ISSUE TITLE
Create Exercise Tracker (Frontend usage)

### ISSUE THREAD

**Issue by devlargs** [devlargs/freecodecamp-projects#54]
- [x] Create POST /api/exercise/new-user
- [x] Create GET /api/exercise/users
- [x] Create POST /api/exercise/add
- [x] Create GET /api/exercise/log/_id
