### ISSUE TITLE
Create Issue Tracker (Backend)

### ISSUE THREAD

**Issue by devlargs** [devlargs/freecodecamp-projects#63]
- [x] POST /api/issues/kanban
- [x] PUT /api/issues/kanban
- [x] DELETE /api/issues/kanban
- [x] GET /api/issues/kanban
- [x] GET /api/issues/kanban?open=false
